### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by naricrow** [naricrow/protospace--user_id#1]
自身のProtoSpaceのURL（本番環境）https://protospace-39580.onrender.com/

**Comment by shodai-ito** [comment]
@naricrow さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`ユーザー管理機能`**
- [x] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されていること**
要件通り、敬称まで表示させましょう。

### **`プロトタイプ詳細機能`**
- [x] **ログイン・ログアウトの状態に関わらず、プロダクトの情報（プロトタイプ名・投稿者・画像・ キャッチコピー・コンセプト）が表示されていること**
プロトタイプ名・キャッチコピー・コンセプトが正しく表示されていません。

### **`編集機能`**
- [x] **正しく編集できた場合は、詳細ページへ遷移すること**
編集が完了するとトップページに遷移してしまいます。

### **`ユーザー詳細機能`**
- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
プロトタイプ詳細ページに表示されるプロトタイプ投稿者名をクリックしても、該当のユーザー詳細ページに遷移できません。

### **`その他`**
- [x] **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できること**
ログアウト状態でユーザー詳細ページに遷移できません。

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他人のプロトタイプ編集ページに遷移できでしまいます。
【チェック方法】
先ず、ユーザーAで投稿したプロトタイプの編集ページURLをコピー。
次に、ユーザーBでログインし、そのURLを直接入力した際に、トップページへリダイレクトされれば正常な挙動。

修正が完了しましたら、**一度ご自身の本番環境で正しく動作しているか確認してみましょう！**
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by moom1122** [comment]
@naricrow さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
